server:
  port: ${PORT_TO_EXPOSE:8081}

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

spring:
  flyway:
    enabled:
  application:
    name: bozhko_project
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/electronic_board_db?useSSL=false
    username: phpadmin
    password: QAz753
  #jpa.hibernate.ddl-auto: update
  jpa.database-platform: org.hibernate.dialect.MySQLDialect
springfox:
  documentation:
    swagger:
      v2:
        path: /v3/api-docs