INSERT INTO oauth_client_details ( client_id,
                                      access_token_validity,
                                      additional_information,
                                      authorities,
                                      authorized_grant_types,
                                      autoapprove,
                                      client_secret,
                                      refresh_token_validity,
                                      resource_ids,
                                      scope,
                                      web_server_redirect_uri)
  VALUES('task-client',
  3600,
  null,
  null,
  'password,refresh_token',
  true,
  '$2a$10$ftGBqfb6LCFoQTbGR8OAf.QGV7e97jwLhboX8OB0OIQzuFH8F5cKa',
  36000,
  null,
  'tasks',
  null,) ;
