--INSERT INTO users (id, login, surname, name, phone, email, password) VALUES (9, 'admin', 'Ivanov', 'Alexey', '+79053451538', 'test9@mail.ru','$2a$10$9OJhEIj3eZo3A7pTbPJC8e6cExaFTs3EOVjwLUS9JK5TXPCtBUx2e');
--INSERT INTO authorities (authority, login) VALUES ('ADMIN', 'admin');
--INSERT INTO authorities (authority, nick) VALUES ('USER', 'Alex'');
--INSERT INTO authorities (authority, nick) VALUES ('USER', 'Jon');
