--INSERT INTO authorities (authority, login) VALUES ('USER', 'Alex');
--INSERT INTO authorities (authority, login) VALUES ('USER', 'Jon');
--INSERT INTO authorities (authority, login) VALUES ('USER','Sam');
--INSERT INTO authorities (authority, login) VALUES ('USER','Yve');
--INSERT INTO authorities (authority, login) VALUES ('USER','Laur');
--INSERT INTO authorities (authority, login) VALUES ('USER','Miranda');
--INSERT INTO authorities (authority, login) VALUES ('USER','Ima');
